In [4]:
import os
os.chdir('..')
import sys
sys.path.append("/workspace/src")

In [5]:
from util.misc import load

In [6]:
l = load('../models/36643623a0d44e25bb0aec2f36d981e7/test_results.pkl')

In [11]:
{k: v.shape for k, v in l.items()}

{'index': (24888,), 'pred': (24888, 17, 3), 'pose3d': (24888, 17, 3)}

In [10]:
l['index'].shape

(24888,)

In [1]:
import numpy as np

In [6]:
shape = [1024, 1, 51]
pred_3d = np.arange(np.prod(shape)).reshape(shape)

In [7]:
tau = 1
pred_3d[:-tau, ] - pred_3d[tau:, ]

array([[[-51, -51, -51, ..., -51, -51, -51]],

       [[-51, -51, -51, ..., -51, -51, -51]],

       [[-51, -51, -51, ..., -51, -51, -51]],

       ...,

       [[-51, -51, -51, ..., -51, -51, -51]],

       [[-51, -51, -51, ..., -51, -51, -51]],

       [[-51, -51, -51, ..., -51, -51, -51]]])

In [2]:
frame_start = np.array([0,0,10,10,10,20,20,20,20,30,30,30,30,30,30])

In [20]:
from itertools import chain
bs = 2
idxs = np.arange(len(frame_start))
batch_idxs = []
for start_idx in np.unique(frame_start):
    frame_idx = idxs[frame_start == start_idx]
    split_idx = np.arange(len(frame_idx))[bs::bs]
    batch_start_end_idx = zip(chain([0], split_idx), chain(split_idx, [None]))
    batch_idxs += list(frame_idx[i : j] for i, j in batch_start_end_idx)

In [21]:
batch_idxs

[array([0, 1]),
 array([2, 3]),
 array([4]),
 array([5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12]),
 array([13, 14])]

[array([ 9, 10]), array([11, 12]), array([13, 14])]